pipeline {
    agent any

	tools {
		maven "MAVEN"
		jdk "JAVA"
	}
	
	environment {
		//Will require Pipeline Utilities Steps Plugin
		MICROSERVICE_VERSION = readMavenPom().getVersion();
		MICROSERVICE_IMAGE = readMavenPom().getArtifactId();
	}
    
	stages {
        stage('Build Microservice') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
		stage('UI Setup') {
		    steps {
			   sh 'cd web-app && npm install'
			}
		}
		stage('UI Test') {
		    steps {
			   sh 'cd web-app/test/unit && au test --coverage'
			}
			post {
                success {
                    junit 'web-app/test/junit/*.xml' 
                }
            }
		}
		stage('UI Build') {
		    steps {
			    sh 'cd web-app && au build --env prod'
			}
		}
		stage('Prepare Installer') {
		    environment {
			   POM_VERSION = sh (returnStdout: true, script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout").trim();
			}
		    steps {
			    script {
				    pom = readMavenPom(file: 'pom.xml')
				    projectArtifactId = pom.getArtifactId();
					echo 'TTTT version is ${projectArtifactId} and ${POM_ARTIFACTID}:${POM_VERSION} '
				}
				echo 'version is ${projectArtifactId} ${projectVersion} and ${POM_ARTIFACTID}:${POM_VERSION} '
			    sh 'cp "target/stamp-imageparsing-3.0.0-SNAPSHOT.jar" "web-app/lib"'
			}
		}
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}