pipeline {
    agent any

	tools {
		maven "MAVEN"
		jdk "JAVA"
	}
	
	environment {
		//Will require Pipeline Utilities Steps Plugin
		MICROSERVICE_VERSION = readMavenPom().getVersion();
		MICROSERVICE_IMAGE = readMavenPom().getArtifactId();
	}
    
	stages {
        stage('Build Microservice') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
		stage('UI Setup') {
		    steps {
			   sh 'cd web-app && npm install'
			}
		}
		stage('UI Test') {
		    steps {
			   sh 'cd web-app/test/unit && au test --coverage'
			}
			post {
                success {
                    junit 'web-app/test/junit/*.xml' 
                }
            }
		}
		stage('UI Build') {
		    steps {
			    sh 'cd web-app && au build --env prod'
			}
		}
		stage('Prepare Installer') {
		    steps {
				echo 'version is ${MICROSERVICE_VERSION} ${MICROSERVICE_IMAGE}'
				def MICROSERVICE_VERSION2 = readMavenPom().getVersion();
				def MICROSERVICE_IMAGE2 = readMavenPom().getArtifactId();
				echo 'version is ${MICROSERVICE_VERSION2} ${MICROSERVICE_IMAGE2}'
			    sh 'cp "target/stamp-imageparsing-3.0.0-SNAPSHOT.jar" "web-app/lib"'
			}
		}
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}